:_mod-docs-content-type: PROCEDURE

:experimental:

[id="proc_configuring-a-wireguard-server-by-using-nm-connection-editor_{context}"]
= Configuring a WireGuard server by using nm-connection-editor

[role="_abstract"]
You can configure the WireGuard server by creating a connection profile in NetworkManager. Use this method to let NetworkManager manage the WireGuard connection.



.Prerequisites

* You have generated the public and private key for both the server and client.

* You know the following information:
+
** The private key of the server
** The static tunnel IP addresses and subnet masks of the client
** The public key of the client
** The static tunnel IP addresses and subnet masks of the server



.Procedure

. Open a terminal, and enter:
+
[literal,subs="+quotes"]
....
# *nm-connection-editor*
....

. Add a new connection by clicking the btn:[+] button.

. Select the `WireGuard` connection type, and click btn:[Create].

. Optional: Update the connection name.

. On the `General` tab, select `Connect automatically with priority`. Optionally, set a priority value.

. On the `WireGuard` tab:

.. Enter the name of the virtual interface, such as `wg0`, that NetworkManager should assign to the connection.

.. Enter the private key of the server.

.. Set the listen port number, such as `51820`, for incoming WireGuard connections.
+
Always set a fixed port number on hosts that receive incoming WireGuard connections. If you do not set a port, WireGuard uses a random free port each time you activate the interface.

.. Click btn:[Add] to add peers:

... Enter the public key of the client.

... Set the `Allowed IPs` field to the tunnel IP addresses of the client that are allowed to send data to this server.

... Click btn:[Apply].

. On the `IPv4 Settings` tab:

.. Select `Manual` in the `Method` list.

.. Click btn:[Add] to enter the tunnel IPv4 address and the subnet mask. Leave the `Gateway` field empty.

. On the `IPv6 Settings` tab:

.. Select `Manual` in the `Method` list.

.. Click btn:[Add] to enter the tunnel IPv6 address and the subnet mask. Leave the `Gateway` field empty.

. Click btn:[Save] to store the connection profile.

. If you use this host in a network with DHCP or Stateless Address Autoconfiguration (SLAAC), the connection can be vulnerable to being redirected. For details and mitigation steps, see xref:assigning-a-vpn-connection-to-a-dedicated-routing-table-to-prevent-the-connection-from-bypassing-the-tunnel_assembly_setting-up-a-wireguard-vpn[Assigning a VPN connection to a dedicated routing table to prevent the connection from bypassing the tunnel].


.Verification

. Display the interface configuration of the `wg0` device:
+
[literal,subs="+quotes"]
....
# *wg show __wg0__*
interface: __wg0__
  public key: __UtjqCJ57DeAscYKRfp7cFGiQqdONRn69u249Fa4O6BE=__
  private key: (hidden)
  listening port: __51820__

peer: __bnwfQcC8/g2i4vvEqcRUM2e6Hi3Nskk6G9t4r26nFVM=__
  allowed ips: __192.0.2.2/32, 2001:db8:1::2/128__
....
+
To display the private key in the output, use the `WG_HIDE_KEYS=never wg show __wg0__` command.

. Display the IP configuration of the `wg0` device:
+
[literal,subs="+quotes"]
....
# *ip address show __wg0__*
__20__: __wg0__: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet __192.0.2.1/24__ brd __192.0.2.255__ scope global noprefixroute wg0
       valid_lft forever preferred_lft forever
    inet6 __2001:db8:1::1/32__ scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 __fe80::3ef:8863:1ce2:844/64__ scope link noprefixroute
       valid_lft forever preferred_lft forever
....


.Next steps

ifdef::networking-title[]
* xref:proc_configuring-firewalld-on-a-wireguard-server-by-using-the-graphical-interface_assembly_setting-up-a-wireguard-vpn[Configure the firewalld service on the WireGuard server].
endif::[]

ifndef::networking-title[]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/{ProductNumberLink}/html/configuring_and_managing_networking/assembly_setting-up-a-wireguard-vpn_configuring-and-managing-networking#proc_configuring-firewalld-on-a-wireguard-server-by-using-the-graphical-interface_assembly_setting-up-a-wireguard-vpn[Configure the firewalld service on the WireGuard server]
endif::[]

