:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-firewalld-on-a-wireguard-server-by-using-the-command-line_{context}"]
= Configuring `firewalld` on a WireGuard server by using the command line

[role="_abstract"]
Configure the `firewalld` service on the WireGuard server, allowing incoming connections from clients. If clients need to use the server as their default gateway and route all traffic through the tunnel, enable also masquerading.


.Procedure

. Open the WireGuard port for incoming connections in the `firewalld` service:
+
[literal,subs="+quotes"]
....
# *firewall-cmd --permanent --add-port=51820/udp --zone=public*
....

. If clients should route all traffic through the tunnel and use the WireGuard server as the default gateway, enable masquerading for the `public` zone:
+
[literal,subs="+quotes"]
....
# *firewall-cmd --permanent --zone=public --add-masquerade*
....

. Reload the `firewalld` rules.
+
[literal,subs="+quotes"]
....
# *firewall-cmd --reload*
....



.Verification

* Display the configuration of the `public` zone:
+
[literal,subs="+quotes"]
....
# *firewall-cmd --list-all*
public (active)
  ...
  ports: 51820/udp
  masquerade: yes
  ...
....


