:_newdoc-version: 2.18.5
:_template-generated: 2025-07-15
:_mod-docs-content-type: PROCEDURE

[id="protecting-the-ipsec-nss-database-with-a-password_{context}"]
= Protecting the IPsec NSS database with a password

[role="_abstract"]
By default, only the root user can access the IPsec Network Security Services (NSS) database in the `/var/lib/ipsec/nss/` directory. You can additionally protect the database with a password. This is required if you run RHEL in Federal Information Processing Standard (FIPS) mode.


.Prerequisites

* The `/var/lib/ipsec/nss/` directory contains the NSS database.


.Procedure

. Enable password protection for the Libreswan NSS database:
+
[subs="+quotes"]
....
# *certutil -W -d /var/lib/ipsec/nss/*
....

. Enter the current password:
+
[source,txt,subs="+quotes"]
....
Enter Password or Pin for "NSS Certificate DB": _<password>_
....
+
If the database is currently not protected by a password, press kbd:[Enter].

. Enter the new password:
+
[source,txt,subs="+quotes"]
....
Enter new password: _<new_password>_
Re-enter password: _<new_password>_
....

. To unlock the database, the `ipsec` service requires the `/etc/ipsec.d/nsspassword` file. Create the file with the following content:

** If the host does not run in FIPS mode:
+
[source,txt,subs="+quotes"]
....
NSS Certificate DB:__<password>__
....

** If the host runs in FIPS mode:
+
[source,txt,subs="+quotes"]
....
NSS FIPS 140-2 Certificate DB:__<password>__
....

. Set secure permissions on the `/etc/ipsec.d/nsspassword` file:
+
[subs="+quotes"]
....
# *chmod 600 /etc/ipsec.d/nsspassword*
# *chown root:root /etc/ipsec.d/nsspassword*
....

. Restart the `ipsec` service:
+
[subs="+quotes"]
....
# *systemctl restart ipsec*
....


.Verification

. Verify that the `ipsec` service is running:
+
[subs="+quotes"]
....
# *systemctl is-active ipsec*
....
+
If the command returns `active`, the service successfully uses the password file to unlock the NSS database.

. Perform an action on the NSS database that requires the password. For example, display the private keys:
+
[subs="+quotes"]
....
# *certutil -K -d /var/lib/ipsec/nss/*
certutil: Checking token "NSS Certificate DB" in slot "NSS User Private Key and Certificate Services"
Enter Password or Pin for "NSS Certificate DB":
....
+
Verify that the command prompts for the password.

