:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-a-wireguard-client-by-using-nm-connection-editor_{context}"]
= Configuring a WireGuard client by using nm-connection-editor

[role="_abstract"]
You can configure a WireGuard client by creating a connection profile in NetworkManager. Use this method to let NetworkManager manage the WireGuard connection.



.Prerequisites

* You have generated the public and private key for both the server and client.

* You know the following information:
+
** The private key of the client
** The static tunnel IP addresses and subnet masks of the client
** The public key of the server
** The static tunnel IP addresses and subnet masks of the server



.Procedure

. Open a terminal, and enter:
+
[literal,subs="+quotes"]
....
# *nm-connection-editor*
....

. Add a new connection by clicking the btn:[+] button.

. Select the *WireGuard* connection type, and click btn:[Create].

. Optional: Update the connection name.

. Optional: On the *General* tab, select *Connect automatically with priority*.

. On the *WireGuard* tab:

.. Enter the name of the virtual interface, such as `wg0`, that NetworkManager should assign to the connection.

.. Enter client's private key.

.. Click btn:[Add] to add peers:

... Enter the public key of the server.

... Set the *Allowed IPs* field. For example, set it to:
+
* The tunnel IP addresses of the server to allow only the server to communicate with this client.
* `0.0.0.0/0;::/0;` to allow any remote IPv4 and IPv6 address to communicate with this client. Use this setting to route all traffic through the tunnel and use the WireGuard server as default gateway.
+
Note that routing all traffic through the tunnel can impact the connectivity to other hosts based on the server routing and firewall configuration.

... Enter the hostname or IP address and port of the WireGuard server into the *Endpoint* field. Use the following format: `_<hostname_or_IP<_:__<port_number>__`

... Optional: If you use the client in a network with network address translation (NAT) or if a firewall closes the UDP connection after some time of inactivity, set a persistent keep alive interval in seconds. In this interval, the client sends a keep alive packet to the server.

... Click btn:[Apply].

. On the *IPv4 Settings* tab:

.. Select *Manual* in the *Method* list.

.. Click btn:[Add] to enter the tunnel IPv4 address and the subnet mask.

.. If you want to route all traffic through the tunnel, set the tunnel IPv4 address of the server in the *Gateway* field. Otherwise, leave the field empty.
+
Routing all IPv4 traffic through the tunnel requires that you included `0.0.0.0/0` in the *Allowed IPs* field on this client.

. On the *IPv6 Settings* tab:

.. Select *Manual* in the *Method* list.

.. Click btn:[Add] to enter the tunnel IPv6 address and the subnet mask.

.. If you want to route all traffic through the tunnel, set the tunnel IPv6 address of the server in the *Gateway* field. Otherwise, leave the field empty.
+
Routing all IPv4 traffic through the tunnel requires that you included `::/0` in the *Allowed IPs* field on this client.

. Click btn:[Save] to store the connection profile.

. If you use this host in a network with DHCP or Stateless Address Autoconfiguration (SLAAC), the connection can be vulnerable to being redirected. For details and mitigation steps, see xref:assigning-a-vpn-connection-to-a-dedicated-routing-table-to-prevent-the-connection-from-bypassing-the-tunnel_assembly_setting-up-a-wireguard-vpn[Assigning a VPN connection to a dedicated routing table to prevent the connection from bypassing the tunnel].


.Verification

. Ping the IP addresses of the server:
+
[literal,subs="+quotes"]
....
# *ping 192.0.2.1*
# *ping6 2001:db8:1::1*
....

. Display the interface configuration of the `wg0` device:
+
[literal,subs="+quotes"]
....
# *wg show wg0*
interface: wg0
  public key: bnwfQcC8/g2i4vvEqcRUM2e6Hi3Nskk6G9t4r26nFVM=
  private key: (hidden)
  listening port: 51820

peer: UtjqCJ57DeAscYKRfp7cFGiQqdONRn69u249Fa4O6BE=
  endpoint: server.example.com:51820
  allowed ips: 192.0.2.1/32, 2001:db8:1::1/128
  latest handshake: 1 minute, 41 seconds ago
  transfer: 824 B received, 1.01 KiB sent
  persistent keepalive: every 20 seconds
....
+
To display the private key in the output, use the `WG_HIDE_KEYS=never wg show wg0` command.
+
Note that the output only has the `latest handshake` and `transfer` entries if you have already sent traffic through the VPN tunnel.

. Display the IP configuration of the `wg0` device:
+
[literal,subs="+quotes"]
....
# *ip address show wg0*
10: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 192.0.2.2/24 brd 192.0.2.255 scope global noprefixroute wg0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1::2/32 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::73d9:6f51:ea6f:863e/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
....


