:_mod-docs-content-type: CONCEPT
[id="network-interface-naming-schemes_{context}"]
= Network interface naming schemes

[role="_abstract"]
The `udev` device manager uses certain stable interface attributes that device drivers provide to generate consistent device names.

If a new `udev` version changes how the service creates names for certain interfaces, {RH} adds a new scheme version and documents the details in the `systemd.net-naming-scheme(7)` man page on your system. By default, {ProductName} ({ProductShortName}) {ProductNumber} uses the `rhel-{ProductNumber}.0` naming scheme, even if you install or update to a later minor version of {ProductShortName}.

ifeval::[{ProductNumber} >= 9]
// This feature was not backported to RHEL 8
To prevent new drivers from providing more or other attributes for a network interface, the `rhel-net-naming-sysattrs` package provides the `/usr/lib/udev/hwdb.d/50-net-naming-sysattr-allowlist.hwdb` database. This database defines which `sysfs` values the `udev` service can use to create network interface names. The entries in the database are also versioned and influenced by the scheme version.

[NOTE]
====
On {ProductShortName} 9.4 and later, you can also use all `rhel-8.*` naming schemes.
// Once https://issues.redhat.com/browse/RHEL-23473 is implemented, uncomment the following line:
//For example, during the upgrade to {ProductShortName} {ProductNumber}, the `Leapp` utility automatically adds the `net.naming-scheme=__<rhel-8-scheme>__` option to the command line of {ProductShortName} {ProductNumber} kernels. This prevents creating different interface names after upgrades.
====
endif::[]

If you want to use a scheme other than the default, you can xref:switching-to-a-different-network-interface-naming-scheme_consistent-network-interface-device-naming[switch the network interface naming scheme].

For further details about the naming schemes for different device types and platforms, see the `systemd.net-naming-scheme(7)` man page on your system.

