:_mod-docs-content-type: CONCEPT

[id="differences-between-the-network-and-network-online-systemd-target_{context}"]
= Differences between the `network` and `network-online` systemd target

[role="_abstract"]
The `network` target indicates that the network management stack has been started, and the `network-online` target is to actively wait until the network is up and a usable network connection is available.

Systemd maintains the `network` and `network-online` target units. The special units such as `NetworkManager-wait-online.service`, have `WantedBy=network-online.target` and `Before=network-online.target` parameters. If enabled, these units get started with `network-online.target` and delay the target to be reached until some form of network connectivity is established. They delay the `network-online` target until the network is connected.

The `network-online` target starts a service, which adds substantial delays to further execution. Systemd automatically adds dependencies with `Wants` and `After` parameters for this target unit to all the System V (SysV) `init` script service units with a Linux Standard Base (LSB) header referring to the `$network` facility. The LSB header is metadata for `init` scripts. You can use it to specify dependencies. This is similar to the `systemd` target.

The `network` target does not significantly delay the execution of the boot process. Reaching the `network` target means that the service that is responsible for setting up the network has started. However, it does not mean that a network device was configured. This target is important during the shutdown of the system. For example, if you have a service that was ordered after the `network` target during bootup, then this dependency is reversed during the shutdown. The network does not get disconnected until your service has been stopped. All mount units for remote network file systems automatically start the `network-online` target unit and order themselves after it.

[NOTE]
====
The `network-online` target unit is only useful during the system startup. After the system has completed booting up, this target does not track the online state of the network. Therefore, you cannot use `network-online` to monitor the network connection. This target provides a one-time system startup concept.
====

