:_mod-docs-content-type: PROCEDURE

[id="proc_changing-a-hostname-using-hostnamectl_{context}"]
= Changing a hostname by using `hostnamectl`

[role="_abstract"]
You can use the `hostnamectl` utility to update the hostname.

By default, `hostnamectl` sets the following hostname types:

* Static hostname: Stored in the `/etc/hostname` file. Typically, services use this name as the hostname.
* Pretty hostname: A descriptive name, such as `Proxy server in data center A`.
* Transient hostname: A fall-back value that is typically received from the network configuration.


.Procedure

. Optional: Display the current hostname setting:
+
[subs="+quotes"]
....
# *hostnamectl status --static*
_old-hostname.example.com_
....

. Set the new hostname:
+
[subs="+quotes"]
....
# *hostnamectl set-hostname _new-hostname.example.com_*
....
+
This command sets the static and transient hostname to the new value. To set only a specific type, pass the `--static`, `--pretty`, or `--transient` option to the command.

. The `hostnamectl` utility automatically restarts the `systemd-hostnamed` to activate the new name. For the changes to take effect, reboot the host:
+
[subs="+quotes"]
....
# *reboot*
....
+
Alternatively, if you know which services use the hostname:

.. Restart all services that only read the hostname when the service starts:
+
[subs="+quotes"]
....
# *systemctl restart _<service_name>_*
....

.. Active shell users must re-login for the changes to take effect.


.Verification

* Display the hostname:
+
[subs="+quotes"]
....
# *hostnamectl status --static*
_new-hostname.example.com_
....

