:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-vlan-tagging-by-using-nmstatectl_{context}"]
= Configuring VLAN tagging by using `nmstatectl`

[role="_abstract"]
You can use the declarative Nmstate API to configure a Virtual Local Area Network VLAN. Nmstate ensures that the result matches the configuration file or rolls back the changes.

Depending on your environment, adjust the YAML file accordingly. For example, to use different devices than Ethernet adapters in the VLAN, adapt the `base-iface` attribute and `type` attributes of the ports you use in the VLAN.


.Prerequisites

* To use Ethernet devices as ports in the VLAN, the physical or virtual Ethernet devices must be installed on the server.
* The `nmstate` package is installed.


.Procedure

. Create a YAML file, for example `~/create-vlan.yml`, with the following content:
+
[source,yaml,subs="+quotes"]
....
---
interfaces:
- name: vlan10
  type: vlan
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 24
    dhcp: false
  ipv6:
    enabled: true
    address:
    - ip: 2001:db8:1::1
      prefix-length: 64
    autoconf: false
    dhcp: false
  vlan:
    base-iface: enp1s0
    id: 10
- name: enp1s0
  type: ethernet
  state: up

routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 192.0.2.254
    next-hop-interface: vlan10
  - destination: ::/0
    next-hop-address: 2001:db8:1::fffe
    next-hop-interface: vlan10

dns-resolver:
  config:
    search:
    - example.com
    server:
    - 192.0.2.200
    - 2001:db8:1::ffbb
....
+
These settings define a VLAN with ID 10 that uses the `enp1s0` device. As the child device, the VLAN connection has the following settings:
+
* A static IPv4 address - `192.0.2.1` with the `/24` subnet mask
* A static IPv6 address - `2001:db8:1::1` with the `/64` subnet mask
* An IPv4 default gateway - `192.0.2.254`
* An IPv6 default gateway - `2001:db8:1::fffe`
* An IPv4 DNS server - `192.0.2.200`
* An IPv6 DNS server - `2001:db8:1::ffbb`
* A DNS search domain - `example.com`

. Apply the settings to the system:
+
[literal,subs="+quotes"]
....
# *nmstatectl apply ~/create-vlan.yml*
....



.Verification

. Display the status of the devices and connections:
+
[literal,subs="+quotes"]
....
# *nmcli device status*
DEVICE      TYPE      STATE      CONNECTION
vlan10      vlan      *connected*  vlan10
....

. Display all settings of the connection profile:
+
[literal,subs="+quotes"]
....
# *nmcli connection show vlan10*
connection.id:              vlan10
connection.uuid:            1722970f-788e-4f81-bd7d-a86bf21c9df5
connection.stable-id:       --
connection.type:            vlan
connection.interface-name:  vlan10
...
....

. Display the connection settings in YAML format:
+
[literal,subs="+quotes"]
....
# *nmstatectl show vlan10*
....

