:_newdoc-version: 2.18.5
:_template-generated: 2025-07-16
:_mod-docs-content-type: PROCEDURE

[id="configuring-tcp-fallback-for-an-ipsec-vpn-connection_{context}"]
= Configuring TCP fallback for an IPsec VPN connection

[role="_abstract"]
Standard IPsec VPNs can fail on restrictive networks that block the UDP and Encapsulating Security Payload (ESP) protocols. To ensure connectivity in such environments, Libreswan can encapsulate all VPN traffic within a TCP connection.

[IMPORTANT]
====
Encapsulating VPN packets within TCP can reduce throughput and increase latency. For this reason, use TCP encapsulation only as a fallback option or if UDP-based connections are consistently blocked in your environment.
====


.Prerequisites

* The IPsec connection is configured.


.Procedure

. Edit the `/etc/ipsec.conf` file, and make the following changes in the `config setup` section:

.. Configure Libreswan to listen on a TCP port:
+
[source,bash]
----
listen-tcp=yes
----

.. By default, Libreswan listens on port 4500. If you want to use a different port, enter:
+
[source,bash,subs="+quotes"]
----
tcp-remoteport=_<port_number>_
----

.. Decide whether TCP should be used as a fallback option if UDP is not available or permanent:

*** As a fallback option, enter:
+
[source,bash]
----
enable-tcp=fallback
retransmit-timeout=5s
----
+
By default, Libreswan waits 60 seconds after a failed attempt to connect by using UDP before retrying the connection over TCP. Lowering the `retransmit-timeout` value shortens the delay, enabling the fallback protocol to initiate more quickly.

*** As a permanent replacement for UDP, enter:
+
[source,bash]
----
enable-tcp=yes
----

. Restart the `ipsec` service:
+
[subs="+quotes"]
....
# *systemctl restart ipsec*
....

. If you configured a TCP port other than the default 4500, open the port in the firewall:
+
[subs="+quotes"]
....
# *firewall-cmd --permanent --add-port=_<tcp_port>_/tcp*
# *firewall-cmd --reload*
....

. Repeat the procedure on the peers that use this gateway.

