:_mod-docs-content-type: PROCEDURE

[id="configuring-a-network-bridge-by-using-nmcli_{context}"]
= Configuring a network bridge by using `nmcli`

[role="_abstract"]
To configure a network bridge on the command line, use the `nmcli` utility.


.Prerequisites

* Two or more physical or virtual network devices are installed on the server.

ifeval::[{ProductNumber} == 9]
* The host runs on {RHEL} 9.4 or later. This version introduced the `port-type`, `controller`, `connection.autoconnect-ports` options used in this procedure. Previous RHEL versions instead use `slave-type`, `master`, and `connection.autoconnect-slaves`.
endif::[]

* To use Ethernet devices as ports of the bridge, the physical or virtual Ethernet devices must be installed on the server.

* To use team, bond, or VLAN devices as ports of the bridge, you can either create these devices while you create the bridge or you can create them in advance as described in:

ifdef::networking-title[]
** xref:configuring-a-network-team-by-using-nmcli_configuring-network-teaming[Configuring a network team by using nmcli]
** xref:configuring-a-network-bond-by-using-nmcli_configuring-network-bonding[Configuring a network bond by using nmcli]
** xref:configuring-vlan-tagging-by-using-nmcli_configuring-vlan-tagging[Configuring VLAN tagging by using nmcli]
endif::[]

ifndef::networking-title[]
** link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/{ProductNumberLink}/html/configuring_and_managing_networking/configuring-network-teaming_configuring-and-managing-networking#configuring-a-network-team-by-using-nmcli_configuring-network-teaming[Configuring a network team using commands]
** link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/{ProductNumberLink}/html/configuring_and_managing_networking/configuring-network-teaming_configuring-and-managing-networking#configuring-a-network-bond-by-using-nmcli_configuring-network-bonding[Configuring a network bond by using nmcli]
** link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/{ProductNumberLink}/html/configuring_and_managing_networking/configuring-vlan-tagging_configuring-and-managing-networking#configuring-vlan-tagging-by-using-nmcli_configuring-vlan-tagging[Configuring VLAN tagging by using nmcli]
endif::[]


.Procedure

. Create a bridge interface:
+
[literal,subs="+quotes"]
....
# *nmcli connection add type bridge con-name bridge0 ifname bridge0*
....
+
This command creates a bridge named `bridge0`.

. Display the network interfaces, and note the names of the interfaces you want to add to the bridge:
+
[literal,subs="+quotes"]
....
# *nmcli device status*
DEVICE  TYPE      STATE         CONNECTION
enp7s0  ethernet  disconnected  --
enp8s0  ethernet  disconnected  --
bond0   bond      connected     bond0
bond1   bond      connected     bond1
...
....
+
In this example:
+
* `enp7s0` and `enp8s0` are not configured. To use these devices as ports, add connection profiles in the next step.
* `bond0` and `bond1` have existing connection profiles. To use these devices as ports, modify their profiles in the next step.

. Assign the interfaces to the bridge.

.. If the interfaces you want to assign to the bridge are not configured, create new connection profiles for them:
+
[literal,subs="+quotes,attributes"]
----
# *nmcli connection add type ethernet {NM_port}-type bridge con-name bridge0-port1 ifname enp7s0 {NM_controller} bridge0*
# *nmcli connection add type ethernet {NM_port}-type bridge con-name bridge0-port2 ifname enp8s0 {NM_controller} bridge0*
----
+
These commands create profiles for `enp7s0` and `enp8s0`, and add them to the `bridge0` connection.

.. If you want to assign an existing connection profile to the bridge:

... Set the `{NM_controller}` parameter of these connections to `bridge0`:
+
[literal,subs="+quotes,attributes"]
----
# *nmcli connection modify bond0 {NM_controller} bridge0*
# *nmcli connection modify bond1 {NM_controller} bridge0*
----
+
These commands assign the existing connection profiles named `bond0` and `bond1` to the `bridge0` connection.

... Reactivate the connections:
+
[literal,subs="+quotes"]
....
# *nmcli connection up bond0*
# *nmcli connection up bond1*
....

. Configure the IPv4 settings:

** To set a static IPv4 address, network mask, default gateway, and DNS server to the `bridge0` connection, enter:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify bridge0 ipv4.addresses '192.0.2.1/24' ipv4.gateway '192.0.2.254' ipv4.dns '192.0.2.253' ipv4.dns-search 'example.com' ipv4.method manual*
....

** To use DHCP, no action is required.

** If you plan to use this bridge device as a port of other devices, no action is required.

. Configure the IPv6 settings:

** To set a static IPv6 address, network mask, default gateway, and DNS server to the `bridge0` connection, enter:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify bridge0 ipv6.addresses '2001:db8:1::1/64' ipv6.gateway '2001:db8:1::fffe' ipv6.dns '2001:db8:1::fffd' ipv6.dns-search 'example.com' ipv6.method manual*
....

** To use stateless address autoconfiguration (SLAAC), no action is required.

** If you plan to use this bridge device as a port of other devices, no action is required.

. Optional: Configure further properties of the bridge. For example, to set the Spanning Tree Protocol (STP) priority of `bridge0` to `16384`, enter:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify bridge0 bridge.priority '16384'*
....
+
By default, STP is enabled.


. Activate the connection:
+
[literal,subs="+quotes"]
....
# *nmcli connection up bridge0*
....

. Verify that the ports are connected, and the `CONNECTION` column displays the port's connection name:
+
[literal,subs="+quotes"]
....
# *nmcli  device*
DEVICE   TYPE      STATE      CONNECTION
...
enp7s0   ethernet  connected  bridge0-port1
enp8s0   ethernet  connected  bridge0-port2
....
+
When you activate any port of the connection, NetworkManager also activates the bridge, but not the other ports of it. You can configure that {RHEL} enables all ports automatically when the bridge is enabled:

.. Enable the `connection.autoconnect-{NM_ports}` parameter of the bridge connection:
+
[literal,subs="+quotes,attributes"]
----
# *nmcli connection modify bridge0 connection.autoconnect-{NM_ports} 1*
----

.. Reactivate the bridge:
+
[literal,subs="+quotes"]
....
# *nmcli connection up bridge0*
....


.Verification

* Use the `ip` utility to display the link status of Ethernet devices that are ports of a specific bridge:
+
[literal,subs="+quotes"]
....
# *ip link show master bridge0*
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bridge0 state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:62:61:0e brd ff:ff:ff:ff:ff:ff
4: enp8s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bridge0 state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:9e:f1:ce brd ff:ff:ff:ff:ff:ff
....

* Use the `bridge` utility to display the status of Ethernet devices that are ports of any bridge device:
+
[literal,subs="+quotes"]
....
# *bridge link show*
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master bridge0 state forwarding priority 32 cost 100
4: enp8s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master bridge0 state listening priority 32 cost 100
5: enp9s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master bridge1 state forwarding priority 32 cost 100
6: enp11s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master bridge1 state blocking priority 32 cost 100
...
....
+
To display the status for a specific Ethernet device, use the `bridge link show dev __<ethernet_device_name>__` command.


[role="_additional-resources"]
.Additional resources
* link:https://access.redhat.com/solutions/3068421[NetworkManager duplicates a connection after restart of NetworkManager service (Red Hat Knowledgebase)]
* link:https://access.redhat.com/solutions/5314671[How to configure a bridge with VLAN information? (Red Hat Knowledgebase)]

