:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-a-network-bond-by-using-nmstatectl_{context}"]
= Configuring a network bond by using `nmstatectl`

[role="_abstract"]
You can use the declarative Nmstate API to configure a network bond. Nmstate ensures that the result matches the configuration file or rolls back the changes.

Depending on your environment, adjust the YAML file accordingly. For example, to use different devices than Ethernet adapters in the bond, adapt the `base-iface` attribute and `type` attributes of the ports you use in the bond.


.Prerequisites

* Two or more physical or virtual network devices are installed on the server.

* To use Ethernet devices as ports in the bond, the physical or virtual Ethernet devices must be installed on the server.

* To use team, bridge, or VLAN devices as ports in the bond, set the interface name in the `port` list, and define the corresponding interfaces.

* The `nmstate` package is installed.


.Procedure

. Create a YAML file, for example `~/create-bond.yml`, with the following content:
+
[source,yaml,subs="+quotes"]
....
---
interfaces:
- name: bond0
  type: bond
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 24
    dhcp: false
  ipv6:
    enabled: true
    address:
    - ip: 2001:db8:1::1
      prefix-length: 64
    autoconf: false
    dhcp: false
  link-aggregation:
    mode: active-backup
    port:
    - enp1s0
    - enp7s0
- name: enp1s0
  type: ethernet
  state: up
- name: enp7s0
  type: ethernet
  state: up

routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 192.0.2.254
    next-hop-interface: bond0
    metric: 300
  - destination: ::/0
    next-hop-address: 2001:db8:1::fffe
    next-hop-interface: bond0
    metric: 300

dns-resolver:
  config:
    search:
    - example.com
    server:
    - 192.0.2.200
    - 2001:db8:1::ffbb
....
+
These settings define a network bond with the following settings:
+
* Network interfaces in the bond: `enp1s0` and `enp7s0`
* Mode: `active-backup`
* Static IPv4 address: `192.0.2.1` with a `/24` subnet mask
* Static IPv6 address: `2001:db8:1::1` with a `/64` subnet mask
* IPv4 default gateway: `192.0.2.254`
* IPv6 default gateway: `2001:db8:1::fffe`
* IPv4 DNS server: `192.0.2.200`
* IPv6 DNS server: `2001:db8:1::ffbb`
* DNS search domain: `example.com`

. Apply the settings to the system:
+
[literal,subs="+quotes"]
....
# *nmstatectl apply ~/create-bond.yml*
....



.Verification

. Display the status of the devices and connections:
+
[literal,subs="+quotes"]
....
# *nmcli device status*
DEVICE      TYPE      STATE      CONNECTION
bond0       bond      *connected*  bond0
....

. Display all settings of the connection profile:
+
[literal,subs="+quotes"]
....
# *nmcli connection show bond0*
connection.id:              bond0
connection.uuid:            79cbc3bd-302e-4b1f-ad89-f12533b818ee
connection.stable-id:       --
connection.type:            bond
connection.interface-name:  bond0
...
....

. Display the connection settings in YAML format:
+
[literal,subs="+quotes"]
....
# *nmstatectl show bond0*
....

