:_mod-docs-content-type: PROCEDURE

[id="disabling-dns-processing-in-the-networkmanager-configuration_{context}"]
= Disabling DNS processing in the NetworkManager configuration

[role="_abstract"]
By default, NetworkManager manages DNS settings in the `/etc/resolv.conf` file, and you can configure the order of DNS servers. Alternatively, you can disable DNS processing in NetworkManager if you prefer to manually configure DNS settings in `/etc/resolv.conf`.


.Procedure

. As the root user, create the `/etc/NetworkManager/conf.d/90-dns-none.conf` file with the following content by using a text editor:
+
[source]
....
[main]
dns=none
....

. Reload the `NetworkManager` service:
+
[literal,subs="+quotes"]
....
# **systemctl reload NetworkManager**
....
+
[NOTE]
====
After you reload the service, NetworkManager no longer updates the `/etc/resolv.conf` file. However, the last contents of the file are preserved.
====

. Optional: Remove the `Generated by NetworkManager` comment from `/etc/resolv.conf` to avoid confusion.


.Verification

. Edit the `/etc/resolv.conf` file and manually update the configuration.

. Reload the `NetworkManager` service:
+
[literal,subs="+quotes"]
....
# **systemctl reload NetworkManager**
....

. Display the `/etc/resolv.conf` file:
+
[literal,subs="+quotes"]
....
# **cat /etc/resolv.conf**
....
+
If you successfully disabled DNS processing, NetworkManager did not override the manually configured settings.


.Troubleshooting

* Display the NetworkManager configuration to ensure that no other configuration file with a higher priority overrode the setting:
+
[literal,subs="+quotes"]
....
# *NetworkManager --print-config*
...
dns=none
...
....


[role="_additional-resources"]
.Additional resources
* xref:configuring-the-order-of-dns-servers_configuring-and-managing-networking[Configuring the order of DNS servers using NetworkManager]

