:_mod-docs-content-type: PROCEDURE

[id="configuring-the-dhcp-behavior-of-a-networkmanager-connection_{context}"]
= Configuring the DHCP timeout behavior of a NetworkManager connection

[role="_abstract"]
In a connection profile that uses DHCP, NetworkManager waits, by default, 45 seconds for the DHCP request to complete. You can customize timeout-related settings, to adjust the connection profile to your environment.


.Prerequisites

* A connection that uses DHCP is configured on the host.


.Procedure

. Optional: Set the `ipv4.dhcp-timeout` and `ipv6.dhcp-timeout` properties. For example, to set both options to `30` seconds, enter:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify _<connection_name>_ ipv4.dhcp-timeout 30 ipv6.dhcp-timeout 30*
....
+
Alternatively, set the parameters to `infinity` to configure that NetworkManager does not stop trying to request and renew an IP address until it is successful.

. Optional: Configure the behavior if NetworkManager does not receive an IPv4 address before the timeout:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify _<connection_name>_ ipv4.may-fail _<value>_*
....
+
If you set the `ipv4.may-fail` option to:
+
* `yes`, the status of the connection depends on the IPv6 configuration:
+
** If the IPv6 configuration is enabled and successful, NetworkManager activates the IPv6 connection and no longer tries to activate the IPv4 connection.
** If the IPv6 configuration is disabled or not configured, the connection fails.
+
* `no`, the connection is deactivated. In this case:
+
** If the `autoconnect` property of the connection is enabled, NetworkManager retries to activate the connection as many times as set in the `autoconnect-retries` property. The default is `4`.
** If the connection still cannot acquire a DHCP address, auto-activation fails. Note that after 5 minutes, the auto-connection process starts again to acquire an IP address from the DHCP server.

. Optional: Configure the behavior if NetworkManager does not receive an IPv6 address before the timeout:
+
[literal,subs="+quotes"]
....
# *nmcli connection modify _<connection_name>_ ipv6.may-fail _<value>_*
....

