:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-a-static-ethernet-connection-with-802-1x-network-authentication-by-using-nmstatectl_{context}"]
= Configuring a static Ethernet connection with 802.1X network authentication by using `nmstatectl`

[role="_abstract"]
You can use the declarative Nmstate API to configure an Ethernet connection with 802.1X network authentication. Nmstate ensures that the result matches the configuration file or rolls back the changes.

[NOTE]
====
The `nmstate` library only supports the `TLS` Extensible Authentication Protocol (EAP) method.
====


.Prerequisites

* The network supports 802.1X network authentication.
* The managed node uses NetworkManager.
* The following files required for TLS authentication exist on the client:
** The client key stored is in the `/etc/pki/tls/private/client.key` file, and the file is owned and only readable by the `root` user.
** The client certificate is stored in the `/etc/pki/tls/certs/client.crt` file.
** The Certificate Authority (CA) certificate is stored in the `/etc/pki/tls/certs/ca.crt` file.


.Procedure

. Create a YAML file, for example `~/create-ethernet-profile.yml`, with the following content:
+
[source,yaml,subs="+quotes"]
....
---
interfaces:
- name: enp1s0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 24
    dhcp: false
  ipv6:
    enabled: true
    address:
    - ip: 2001:db8:1::1
      prefix-length: 64
    autoconf: false
    dhcp: false
  802.1x:
    ca-cert: /etc/pki/tls/certs/ca.crt
    client-cert: /etc/pki/tls/certs/client.crt
    eap-methods:
      - tls
    identity: client.example.org
    private-key: /etc/pki/tls/private/client.key
    private-key-password: password
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 192.0.2.254
    next-hop-interface: enp1s0
  - destination: ::/0
    next-hop-address: 2001:db8:1::fffe
    next-hop-interface: enp1s0
dns-resolver:
  config:
    search:
    - example.com
    server:
    - 192.0.2.200
    - 2001:db8:1::ffbb
....
+
These settings define an Ethernet connection profile for the `enp1s0` device with the following settings:
+
* A static IPv4 address - `192.0.2.1` with a `/24` subnet mask
* A static IPv6 address - `2001:db8:1::1` with a `/64` subnet mask
* An IPv4 default gateway - `192.0.2.254`
* An IPv6 default gateway - `2001:db8:1::fffe`
* An IPv4 DNS server - `192.0.2.200`
* An IPv6 DNS server - `2001:db8:1::ffbb`
* A DNS search domain - `example.com`
* 802.1X network authentication using the `TLS` EAP protocol


. Apply the settings to the system:
+
[subs="+quotes"]
....
# *nmstatectl apply ~/create-ethernet-profile.yml*
....


.Verification

* Access resources on the network that require network authentication. 

