:_mod-docs-content-type: PROCEDURE

[id="configuring-vlan-tagging-by-using-nmcli_{context}"]
= Configuring VLAN tagging by using `nmcli`

[role="_abstract"]
You can configure Virtual Local Area Network (VLAN) tagging on the command line using the `nmcli` utility.


.Prerequisites

* The interface you plan to use as a parent to the virtual VLAN interface supports VLAN tags.

* If you configure the VLAN on top of a bond interface:
** The ports of the bond are up.
** The bond is not configured with the `fail_over_mac=follow` option. A VLAN virtual device cannot change its MAC address to match the parent's new MAC address. In such a case, the traffic would still be sent with the incorrect source MAC address.
** The bond is usually not expected to get IP addresses from a DHCP server or IPv6 auto-configuration. Ensure it by setting the `ipv4.method=disable` and `ipv6.method=ignore` options while creating the bond. Otherwise, if DHCP or IPv6 auto-configuration fails after some time, the interface might be brought down.


* The switch, the host is connected to, is configured to support VLAN tags. For details, see the documentation of your switch.


.Procedure

. Display the network interfaces:
+
[subs="+quotes"]
....
# *nmcli device status*
DEVICE   TYPE      STATE         CONNECTION
enp1s0   ethernet  disconnected  enp1s0
bridge0  bridge    connected     bridge0
bond0    bond      connected     bond0
...
....

. Create the VLAN interface. For example, to create a VLAN interface named `vlan10` that uses `enp1s0` as its parent interface and that tags packets with VLAN ID `10`, enter:
+
[subs="+quotes"]
....
# *nmcli connection add type vlan con-name vlan10 ifname vlan10 vlan.parent enp1s0 vlan.id 10*
....
+
Note that the VLAN must be within the range from `0` to `4094`.

. By default, the VLAN connection inherits the maximum transmission unit (MTU) from the parent interface. Optionally, set a different MTU value:
+
[subs="+quotes"]
....
# *nmcli connection modify vlan10 ethernet.mtu 2000*
....

. Configure the IPv4 settings:

** To set a static IPv4 address, network mask, default gateway, and DNS server to the `vlan10` connection, enter:
+
[subs="+quotes"]
....
# *nmcli connection modify vlan10 ipv4.addresses '192.0.2.1/24' ipv4.gateway '192.0.2.254' ipv4.dns '192.0.2.253' ipv4.method manual*
....

** To use DHCP, no action is required.

** If you plan to use this VLAN device as a port of other devices, no action is required.

. Configure the IPv6 settings:

** To set a static IPv6 address, network mask, default gateway, and DNS server to the `vlan10` connection, enter:
+
[subs="+quotes"]
....
# *nmcli connection modify vlan10 ipv6.addresses '2001:db8:1::1/32' ipv6.gateway '2001:db8:1::fffe' ipv6.dns '2001:db8:1::fffd' ipv6.method manual*
....

** To use stateless address autoconfiguration (SLAAC), no action is required.

** If you plan to use this VLAN device as a port of other devices, no action is required.

. Activate the connection:
+
[subs="+quotes"]
....
# *nmcli connection up vlan10*
....



.Verification
* Verify the settings:
+
[subs="+quotes"]
....
# *ip -d addr show vlan10*
4: vlan10@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:72:2f:6e brd ff:ff:ff:ff:ff:ff promiscuity 0
    vlan protocol 802.1Q id 10 <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 192.0.2.1/24 brd 192.0.2.255 scope global noprefixroute vlan10
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1::1/32 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::8dd7:9030:6f8e:89e6/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
....

