:_mod-docs-content-type: PROCEDURE

[id="proc_debugging-an-incorrect-vlan-configuration-using-lldp-information_{context}"]
= Debugging an incorrect VLAN configuration using LLDP information

[role="_abstract"]
If you configured a switch port to use a certain VLAN and a host does not receive these VLAN packets, you can use the Link Layer Discovery Protocol (LLDP) to debug the problem.


.Prerequisites

* The `nmstate` package is installed.
* The switch supports LLDP.
* LLDP is enabled on neighbor devices.


.Procedure

. Create the `~/enable-LLDP-enp1s0.yml` file with the following content:
+
[source,yaml,subs="+quotes"]
....
interfaces:
  - name: __enp1s0__
    type: ethernet
    lldp:
      enabled: true
....

. Use the `~/enable-LLDP-enp1s0.yml` file to enable LLDP on interface `enp1s0`:
+
[literal,subs="+quotes"]
....
# **nmstatectl apply ~/enable-LLDP-enp1s0.yml**
....

. Display the LLDP information:
+
[literal,subs="+quotes"]
....
# **nmstatectl show enp1s0**
- name: enp1s0
  type: ethernet
  state: up
  ipv4:
    enabled: false
    dhcp: false
  ipv6:
    enabled: false
    autoconf: false
    dhcp: false
  lldp:
    enabled: true
    neighbors:
    - - type: 5
        system-name: Summit300-48
      - type: 6
        system-description: Summit300-48 - Version 7.4e.1 (Build 5)
          05/27/05 04:53:11
      - type: 7
        system-capabilities:
        - MAC Bridge component
        - Router
      - type: 1
        _description: MAC address
        chassis-id: 00:01:30:F9:AD:A0
        chassis-id-type: 4
      - type: 2
        _description: Interface name
        port-id: 1/1
        port-id-type: 5
      - type: 127
        ieee-802-1-vlans:
        - name: v2-0488-03-0505
          vid: 488
        oui: 00:80:c2
        subtype: 3
      - type: 127
        ieee-802-3-mac-phy-conf:
          autoneg: true
          operational-mau-type: 16
          pmd-autoneg-cap: 27648
        oui: 00:12:0f
        subtype: 1
      - type: 127
        ieee-802-1-ppvids:
        - 0
        oui: 00:80:c2
        subtype: 2
      - type: 8
        management-addresses:
        - address: 00:01:30:F9:AD:A0
          address-subtype: MAC
          interface-number: 1001
          interface-number-subtype: 2
      - type: 127
        ieee-802-3-max-frame-size: 1522
        oui: 00:12:0f
        subtype: 4
  mac-address: 82:75:BE:6F:8C:7A
  mtu: 1500
....

. Verify the output to ensure that the settings match your expected configuration. For example, the LLDP information of the interface connected to the switch shows that the switch port this host is connected to uses VLAN ID `448`:
+
[source,yaml]
....
- type: 127
        ieee-802-1-vlans:
        - name: v2-0488-03-0505
          vid: 488
....
+
If the network configuration of the `enp1s0` interface uses a different VLAN ID, change it accordingly.


[role="_additional-resources"]
.Additional resources
ifdef::networking-title[]
* xref:configuring-vlan-tagging_configuring-and-managing-networking[Configuring VLAN tagging]
endif::[]

ifndef::networking-title[]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/{ProductNumberLink}/html/configuring_and_managing_networking/configuring-vlan-tagging_configuring-and-managing-networking[Configuring VLAN tagging]
endif::[]

