:_newdoc-version: 2.18.5
:_template-generated: 2025-07-22
:_mod-docs-content-type: REFERENCE

[id="mismatched-configurations"]
= Mismatched Configurations

[role="_abstract"]
VPN connections fail if the endpoints are not configured with matching Internet Key Exchange (IKE) versions, algorithms, IP address ranges, or pre-shared keys (PSK). If you identify a mismatch, you must align the settings on both endpoints to resolve the issue.


Remote Peer Not Running IKE/IPsec:: If the connection was refused, an ICMP error is displayed:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
000 "vpn.example.com"[1] 192.0.2.2 #16: ERROR: asynchronous network error report on wlp2s0 (192.0.2.2:500), complainant 198.51.100.1: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
....

Mismatched IKE Algorithms:: The connection fails with a `NO_PROPOSAL_CHOSEN` notification during the initial setup:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
003 "vpn.example.com"[1] 193.110.157.148 #3: dropping unexpected IKE_SA_INIT message containing NO_PROPOSAL_CHOSEN notification; message payloads: N; missing payloads: SA,KE,Ni
....

Mismatched IPsec Algorithms:: The connection fails with a `NO_PROPOSAL_CHOSEN` error after the initial exchange:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
182 "vpn.example.com"[1] 193.110.157.148 #5: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_256 group=MODP2048}
002 "vpn.example.com"[1] 193.110.157.148 #6: IKE_AUTH response contained the error notification NO_PROPOSAL_CHOSEN
....

Mismatched IP Address Ranges (IKEv2):: The remote peer responds with a `TS_UNACCEPTABLE` error:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
1v2 "vpn.example.com" #1: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=MODP2048}
002 "vpn.example.com" #2: IKE_AUTH response contained the error notification TS_UNACCEPTABLE
....

Mismatched IP Address Ranges (IKEv1):: The connection times out during quick mode, with a message indicating the peer did not accept the proposal:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
031 "vpn.example.com" #2: STATE_QUICK_I1: 60 second timeout exceeded after 0 retransmits.  No acceptable response to our first Quick Mode message: perhaps peer likes no proposal
....

Mismatched PSK (IKEv2):: The peer rejects the connection with an `AUTHENTICATION_FAILED` error:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
003 "vpn.example.com" #1: received Hash Payload does not match computed value
223 "vpn.example.com" #1: sending notification INVALID_HASH_INFORMATION to 192.0.2.23:500
....

Mismatched PSK (IKEv1):: The hash payload does not match, making the IKE message unreadable and resulting in an `INVALID_HASH_INFORMATION` error:
+
[subs="+quotes"]
....
# *ipsec auto --up vpn.example.com*
...
002 "vpn.example.com" #1: IKE SA authentication request rejected by peer: AUTHENTICATION_FAILED
....

