:_mod-docs-content-type: REFERENCE

[id="the-different-network-bonding-modes_{context}"]
= The different network bonding modes

[role="_abstract"]
Bonding aggregates multiple network interfaces into a single logical one. The behavior of a bonded interface depends on its bonding policy, also known as mode, which provides either load-balancing or hot standby services.

The Linux bonding driver supports the following modes:

Balance-rr (Mode 0)::
`Balance-rr` uses the round-robin algorithm that sequentially transmits packets from the first available port to the last one. This mode provides load balancing and fault tolerance.
+
This mode requires switch configuration of a port aggregation group, also called EtherChannel or similar port grouping. An EtherChannel is a port link aggregation technology to group multiple physical Ethernet links to one logical Ethernet link. 
+
The drawback of this mode is that it is not suitable for heavy workloads and if TCP throughput or ordered packet delivery is essential.

Active-backup (Mode 1)::
`Active-backup` uses the policy that determines that only one port is active in the bond. This mode provides fault tolerance and does not require any switch configuration.
+
If the active port fails, an alternate port becomes active. The bond sends a gratuitous address resolution protocol (ARP) response to the network. The gratuitous ARP forces the receiver of the ARP frame to update their forwarding table. The `Active-backup` mode transmits a gratuitous ARP to announce the new path to maintain connectivity for the host.
+
The `primary` option defines the preferred port of the bonding interface.

Balance-xor (Mode 2)::

`Balance-xor` uses the selected transmit hash policy to send the packets. This mode provides load balancing, fault tolerance, and requires switch configuration to set up an Etherchannel or similar port grouping.
+
To alter packet transmission and balance transmit, this mode uses the `xmit_hash_policy` option. Depending on the source or destination of traffic on the interface, the interface requires an additional load-balancing configuration. See description xref:ref_xmit-hash-policy-bonding-parameter_configuring-network-bonding[xmit_hash_policy bonding parameter].

Broadcast (Mode 3)::

`Broadcast` uses a policy that transmits every packet on all interfaces. This mode provides fault tolerance and requires a switch configuration to set up an EtherChannel or similar port grouping.
+
The drawback of this mode is that it is not suitable for heavy workloads and if TCP throughput or ordered packet delivery is essential. 

802.3ad (Mode 4)::

`802.3ad` uses the same-named IEEE standard dynamic link aggregation policy. This mode provides fault tolerance. This mode requires switch configuration to set up a Link Aggregation Control Protocol (LACP) port grouping.
+
This mode creates aggregation groups that share the same speed and duplex settings and utilizes all ports in the active aggregator. Depending on the source or destination of traffic on the interface, this mode requires an additional load-balancing configuration.
+
By default, the port selection for outgoing traffic depends on the transmit hash policy. Use the `xmit_hash_policy` option of the transmit hash policy to change the port selection and balance transmit.
+
The difference between the `802.3ad` and the `Balance-xor` is compliance. The `802.3ad` policy negotiates LACP between the port aggregation groups. See description xref:ref_xmit-hash-policy-bonding-parameter_configuring-network-bonding[xmit_hash_policy bonding parameter]

Balance-tlb (Mode 5)::

`Balance-tlb` uses the transmit load balancing policy. This mode provides fault tolerance, load balancing, and establishes channel bonding that does not require any switch support.
+
The active port receives the incoming traffic. In case of failure of the active port, another one takes over the MAC address of the failed port. To decide which interface processes the outgoing traffic, use one of the following modes:

* Value `0`: Uses the hash distribution policy to distribute traffic without load balancing
* Value `1`: Distributes traffic to each port by using load balancing

+
With the bonding option `tlb_dynamic_lb=0`, this bonding mode uses the `xmit_hash_policy` bonding option to balance transmit. The `primary` option defines the preferred port of the bonding interface.

+
See description xref:ref_xmit-hash-policy-bonding-parameter_configuring-network-bonding[xmit_hash_policy bonding parameter].

Balance-alb (Mode 6)::

`Balance-alb` uses an adaptive load balancing policy. This mode provides fault tolerance, load balancing, and does not require any special switch support.
+
This mode includes balance-transmit load balancing (`balance-tlb`) and receive-load balancing for IPv4 and IPv6 traffic. The bonding intercepts ARP replies sent by the local system and overwrites the source hardware address of one of the ports in the bond. ARP negotiation manages the receive-load balancing. Therefore, different ports use different hardware addresses for the server.
+
The `primary` option defines the preferred port of the bonding interface. With the bonding option `tlb_dynamic_lb=0`, this bonding mode uses the `xmit_hash_policy` bonding option to balance transmit. See description xref:ref_xmit-hash-policy-bonding-parameter_configuring-network-bonding[xmit_hash_policy bonding parameter].


ifeval::[{ProductNumber} >= 9]
Additionally, you can use NetworkManager to configure the following mode:

Balance-slb::

The source load balancing (SLB) bonding mode distributes outgoing data streams across multiple network interfaces based on the source address of the traffic and a VLAN hash. This mode does not require any switch configuration.
+
NetworkManager uses the `balance-xor` mode in combination with `nftables` rules to provide SLB. For details about configuring this mode, see the Red Hat Knowledgebase solution link:https://access.redhat.com/solutions/7094905[Configuring a network bond on RHEL with source load balancing].
endif::[]


[role="_additional-resources"]
.Additional resources
* link:https://access.redhat.com/solutions/67546[Which bonding modes work when used with a bridge that virtual machine guests or containers connect to? (Red Hat Knowledgebase)]
* link:https://access.redhat.com/solutions/71883[How are the values for different policies in "xmit_hash_policy" bonding parameter calculated? (Red Hat Knowledgebase)]
